steps:
# Build the Bazel builder and output the version we built with.
- name: 'gcr.io/cloud-builders/bazel'
  args: ['run', '@yarn//:yarn']
- name: 'gcr.io/cloud-builders/bazel'
  args: ['build', '//...', '@program_example//...']
- name: 'gcr.io/cloud-builders/bazel'
  args: ['test', '//...', '@program_example//...']
